spring:
  application:
    name: frontend
  resources:
    static-locations: classpath:web/

server:
  port: 8080
  tomcat:
    accesslog:
      file-date-format: yyyy-MM-dd
      enabled: true

eureka:
  instance:
    hostname: frontend
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 2
#    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka

management:
  security:
    enabled: false
