spring:
  application:
    name: frontend
  resources:
    static-locations: classpath:web/

server:
  port: 8080

eureka:
  instance:
    hostname: frontend
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka