apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: ${REGISTRY}/admin:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000