apiVersion: v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: 192.168.28.12:5000/eureka
        ports:
        - containerPort: 80