apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: ${REGISTRY}/eureka:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 8761