apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: eureka
        image: ${REGISTRY}/frontend:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080