apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zuul-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: zuul
    spec:
      containers:
      - name: eureka
        image: ${REGISTRY}/zuul:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 80