spring:
  application:
    name: zuul
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 100
  resources:
    static-locations: static

server:
  port: 80
  tomcat:
    accesslog:
      file-date-format: yyyy-MM-dd
      enabled: true
      request-attributes-enabled: true
      buffered: true
    basedir: logs
    max-threads: 1000

eureka:
  instance:
    hostname: zuul
#    lease-renewal-interval-in-seconds: 2
#    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 2
    service-url:
      defaultZone: http://eureka:8761/eureka

zuul:
  routes:
    root:
      path: /
      url: http://frontend:8080/html/index.html
    frontend:
      path: /web/**
      serviceId: frontend
    backend:
      path: /api/**
      serviceId: backend-entrance
  retryable: true

management:
  security:
    enabled: false