spring:
  application:
    name: eureka
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 2
  server:
    # 两秒扫描一次注册的服务
    eviction-interval-timer-in-ms: 5000
    # 不强制损坏的服务下线
    enable-self-preservation: true
  client:
    # eureka之间相互注册
    register-with-eureka: true
    # 获取其他服务的注册信息
    fetch-registry: true
    # 两秒同步一次注册信息
    registry-fetch-interval-seconds: 2
    # 向其他机器进行注册
    service-url:
      defaultZone: http://eureka:8761/eureka

management:
  security:
    enabled: false
