spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  instance:
    hostname: eureka
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  server:
    # 两秒扫描一次注册的服务
    eviction-interval-timer-in-ms: 5000
    # 强制损坏的服务下线
    enable-self-preservation: false
  client:
    # eureka之间相互注册
    register-with-eureka: true
    # 获取其他服务的注册信息
    fetch-registry: true
    # 两秒同步一次注册信息
    registry-fetch-interval-seconds: 2
    # 向其他机器进行注册
    service-url:
      defaultZone: http://eureka:8761/eureka

