server:
  port: 8086

eureka:
  instance:
    hostname: backend-pipeline
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 4
    health-check-url-path: /api/health
    status-page-url-path: /api/info
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 2

