spring:
  application:
    name: admin

server:
  port: 8000

eureka:
  instance:
    hostname: admin
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 4
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 2

management:
  security:
    enabled: false